# Generated by Django 6.0.7 on 2026-08-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("user", "Пользователь"), ("manager", "Менеджер")],
                default="user",
                max_length=20,
            ),
        ),
    ]
