# Generated by Django 6.0.7 on 2026-08-02 19:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_mailingattempt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailingattempt",
            name="created_at",
        ),
        migrations.AddField(
            model_name="mailingattempt",
            name="attempt_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата и время попытки",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="mailing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="mailing.mailing",
                verbose_name="Рассылка",
            ),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="server_response",
            field=models.TextField(blank=True, verbose_name="Ответ почтового сервера"),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="status",
            field=models.CharField(
                choices=[("Успешно", "Успешно"), ("Не успешно", "Не успешно")],
                max_length=15,
                verbose_name="Статус",
            ),
        ),
    ]
