# Generated by Django 6.0.7 on 2026-08-02 19:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_remove_mailingattempt_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingattempt",
            name="attempt_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата и время попытки"
            ),
        ),
    ]
